#!/bin/bash

BUS=1
ADDR=0x48

#BYTES=$(i2ctransfer -y $BUS w3@$ADDR 0x01 0xc3 0x83 w1 0x00 r2)
BYTES=$(i2ctransfer -y $BUS w3@$ADDR 0x01 0xd3 0x03 w1 0x00 r2)
HEX=$(printf '%.2x%.2x\n' $BYTES)
SHIFTED=${HEX:0:3}
DEC=$(printf '%d\n' $((16#$SHIFTED)))
SCALED=$(echo "$DEC / 2047 * 4096 / 3300 * 25.85" | bc -l)
echo -e "$SCALED\t\t$DEC\t\t$SHIFTED\t\t$HEX\t\t$BYTES"
echo $SCALED
